#!/usr/bin/env node
/**
 * Build-time environment config generator
 * Reads env vars and writes frontend/env-config.js with all network/contract config.
 * Vercel runs this as the build command; locally run `node scripts/build-env.js`.
 */

const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const e = (key, fallback) => process.env[key] || fallback;

const config = `/**
 * Auto-generated by scripts/build-env.js — do not edit manually.
 * Re-generate: node scripts/build-env.js
 */

// ═══════════════════════════════════════
// NETWORK CONFIGURATION
// ═══════════════════════════════════════

export const ZERO_G_CONFIG = {
  sepolia: {
    chainId: 11155111,
    name: 'Sepolia Testnet',
    rpcUrl: (typeof window !== 'undefined' && window.__POC_ENV__?.SEPOLIA_RPC_URL) || '${e('SEPOLIA_RPC_URL', 'https://rpc.sepolia.org')}',
    explorer: 'https://sepolia.etherscan.io',
    currency: 'ETH',
    isTestnet: true,
    storage: {
      indexer: '${e('ZG_STORAGE_INDEXER', 'https://indexer-storage-testnet-turbo.0g.ai')}',
      evmRpc: '${e('ZG_STORAGE_EVM_RPC', 'https://evmrpc-testnet.0g.ai')}',
      flowContract: '${e('ZG_FLOW_CONTRACT', '0x22E03a6A89B950F1c82ec5e74F8eCa321a105296')}'
    },
    compute: {
      endpoint: '${e('ZG_COMPUTE_ENDPOINT', 'https://broker-testnet.0g.ai')}'
    },
    contracts: {
      agentRegistry: '${e('SEPOLIA_VERIFIER_ADDRESS', '0xe311a113684F5Fd2F983fD7dE59c0D4e6C630C10')}',
      iNFT: '${e('SEPOLIA_INFT_ADDRESS', '0x6afF6B0fb940FFB20B7D8104A1C7c42b9d167f29')}',
      policyEngine: '${e('SEPOLIA_VERIFIER_ADDRESS', '0xe311a113684F5Fd2F983fD7dE59c0D4e6C630C10')}',
      registry: '${e('SEPOLIA_EIP8004_INTEGRATION_ADDRESS', '0x6254651F29e7afEE1c52a1D6Fd4b7B211d2dBed2')}',
      swarm: '${e('SEPOLIA_SOULVAULT_SWARM_ADDRESS', '0x11938021169a5094B5c67389286A1FAe72bdE561')}',
      registryAdapter: '${e('SEPOLIA_ERC8004_REGISTRY_ADAPTER_ADDRESS', '0x56B19562c7d6cB3bCCD0FA78214EFC3928F6eE6a')}'
    },
    riscZeroImageId: '${e('RISC_ZERO_IMAGE_ID', '0xa2ad29fbb85c3aee3a8863ffcb1fa287f537d89473f44df19cb2065834f025d2')}'
  },
  testnet: {
    chainId: 16602,
    name: '0G Testnet',
    rpcUrl: '${e('ZERO_G_CHAIN_RPC', 'https://evmrpc-testnet.0g.ai')}',
    explorer: 'https://chainscan-galileo.0g.ai',
    currency: 'OG',
    isTestnet: true,
    storage: {
      indexer: '${e('ZG_STORAGE_INDEXER', 'https://indexer-storage-testnet-turbo.0g.ai')}',
      evmRpc: '${e('ZERO_G_CHAIN_RPC', 'https://evmrpc-testnet.0g.ai')}',
      flowContract: '${e('ZG_FLOW_CONTRACT', '0x22E03a6A89B950F1c82ec5e74F8eCa321a105296')}'
    },
    compute: {
      endpoint: '${e('ZG_COMPUTE_ENDPOINT', 'https://broker-testnet.0g.ai')}'
    },
    contracts: {
      agentRegistry: '${e('OG_TESTNET_VERIFIER_ADDRESS', '0xe34dab193105f3d7ec6ee4e6172cbe6213108d8b')}',
      iNFT: '${e('OG_TESTNET_INFT_ADDRESS', '0x45c69b7be9dc9a4126053a17a43e664b4ae031a1')}',
      policyEngine: '${e('OG_TESTNET_VERIFIER_ADDRESS', '0xe34dab193105f3d7ec6ee4e6172cbe6213108d8b')}',
      registry: '${e('OG_TESTNET_VERIFIER_ADDRESS', '0xe34dab193105f3d7ec6ee4e6172cbe6213108d8b')}',
      swarm: '${e('OG_TESTNET_SWARM_ADDRESS', '0xa70EB0DF1563708F28285C2DeA2BF31aadFB544D')}',
      registryAdapter: '${e('OG_TESTNET_REGISTRY_ADAPTER_ADDRESS', '0x9De4F1b14660B5f8145a78Cfc0312B1BFb812C46')}'
    },
    riscZeroImageId: '${e('RISC_ZERO_IMAGE_ID', '0xa2ad29fbb85c3aee3a8863ffcb1fa287f537d89473f44df19cb2065834f025d2')}'
  },
  mainnet: {
    chainId: 16661,
    name: '0G Mainnet',
    rpcUrl: '${e('OG_MAINNET_RPC', 'https://evmrpc.0g.ai')}',
    explorer: 'https://chainscan.0g.ai',
    currency: 'OG',
    isTestnet: false,
    // NOTE: Mainnet flow contract differs from testnet — update after mainnet deployment
    storage: {
      indexer: '${e('OG_MAINNET_STORAGE_INDEXER', 'https://indexer-storage.0g.ai')}',
      evmRpc: '${e('OG_MAINNET_RPC', 'https://evmrpc.0g.ai')}',
      flowContract: null // Not yet deployed — guard against accidental use
    },
    compute: {
      endpoint: '${e('OG_MAINNET_COMPUTE', 'https://broker.0g.ai')}'
    },
    // All null — mainnet contracts not yet deployed
    contracts: null
  }
};

// ═══════════════════════════════════════
// DM3 CONFIGURATION
// ═══════════════════════════════════════

export const DM3_CONFIG = {
  defaultDeliveryService: '${e('DM3_DELIVERY_SERVICE_URL', 'https://dm3-delivery-service.vercel.app')}',
  ensTextRecord: 'network.dm3.profile',
  profileVersion: '1.0'
};

// ═══════════════════════════════════════
// CONTRACT ADDRESSES (for viem-client)
// ═══════════════════════════════════════

export const CONTRACT_ADDRESSES = {
  sepolia: {
    inft: ZERO_G_CONFIG.sepolia.contracts.iNFT,
    registry: ZERO_G_CONFIG.sepolia.contracts.registry,
    swarm: ZERO_G_CONFIG.sepolia.contracts.swarm,
    registryAdapter: ZERO_G_CONFIG.sepolia.contracts.registryAdapter,
  },
  og_testnet: {
    inft: ZERO_G_CONFIG.testnet.contracts.iNFT,
    registry: ZERO_G_CONFIG.testnet.contracts.registry,
    swarm: ZERO_G_CONFIG.testnet.contracts.swarm,
    registryAdapter: ZERO_G_CONFIG.testnet.contracts.registryAdapter,
  },
};

// ═══════════════════════════════════════
// NETWORKS (for config-validator)
// ═══════════════════════════════════════

export const Networks = {
  sepolia: {
    id: 'sepolia',
    name: 'Sepolia',
    chainId: ZERO_G_CONFIG.sepolia.chainId,
    rpcUrl: ZERO_G_CONFIG.sepolia.rpcUrl,
    currency: ZERO_G_CONFIG.sepolia.currency,
    explorer: ZERO_G_CONFIG.sepolia.explorer,
    isTestnet: true,
    contracts: {
      inft: ZERO_G_CONFIG.sepolia.contracts.iNFT,
      registry: ZERO_G_CONFIG.sepolia.contracts.registry
    }
  },
  og_testnet: {
    id: 'og_testnet',
    name: '0G Testnet',
    chainId: ZERO_G_CONFIG.testnet.chainId,
    rpcUrl: ZERO_G_CONFIG.testnet.rpcUrl,
    currency: ZERO_G_CONFIG.testnet.currency,
    explorer: ZERO_G_CONFIG.testnet.explorer,
    isTestnet: true,
    contracts: {
      inft: ZERO_G_CONFIG.testnet.contracts.iNFT,
      registry: ZERO_G_CONFIG.testnet.contracts.registry
    }
  },
  og_mainnet: {
    id: 'og_mainnet',
    name: '0G Mainnet',
    chainId: ZERO_G_CONFIG.mainnet.chainId,
    rpcUrl: ZERO_G_CONFIG.mainnet.rpcUrl,
    currency: ZERO_G_CONFIG.mainnet.currency,
    explorer: ZERO_G_CONFIG.mainnet.explorer,
    isTestnet: false,
    // Mainnet contracts not yet deployed
    contracts: { inft: null, registry: null }
  }
};

// ═══════════════════════════════════════
// API CONFIGURATION
// ═══════════════════════════════════════

export const API_CONFIG = {
  defaultPort: '${e('API_PORT', '8420')}',
  oneClawPort: '${e('ONECLAW_PORT', '3456')}'
};
`;

const outPath = path.join(__dirname, '..', 'frontend', 'env-config.js');
fs.writeFileSync(outPath, config, 'utf-8');
console.log(`✓ env-config.js written to ${outPath}`);

// ═══════════════════════════════════════
// Generate env.generated.js — runtime secrets for the frontend
// This file is gitignored and must be regenerated per environment.
// ═══════════════════════════════════════

const envGenerated = `/**
 * Auto-generated by scripts/build-env.js — do not edit manually.
 * Re-generate: node scripts/build-env.js
 *
 * This file injects environment-specific secrets into window.__POC_ENV__
 * so that frontend code can read them at runtime without hardcoding keys.
 * This file is gitignored — never commit it.
 */
window.__POC_ENV__ = {
  SEPOLIA_RPC_URL: '${e('SEPOLIA_RPC_URL', '')}',
  ONECLAW_API_KEY: '${e('ONECLAW_API_KEY', '')}',
  ONECLAW_ENDPOINT: '${e('ONECLAW_ENDPOINT', '')}',
  AGENT_ID: '${e('ONECLAW_AGENT_ID', '')}',
  VAULT_ID: '${e('ONECLAW_VAULT_ID', '')}',
  USER_AUTH_KEY: '${e('USER_AUTH_KEY', '')}',
  OPERATOR_AUTH_KEY: '${e('OPERATOR_AUTH_KEY', '')}',
};
`;

const envGenPath = path.join(__dirname, '..', 'frontend', 'env.generated.js');
fs.writeFileSync(envGenPath, envGenerated, 'utf-8');
console.log(`✓ env.generated.js written to ${envGenPath}`);
