// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./interfaces/IRiscZeroVerifier.sol";

/// @title RiscZeroGroth16Verifier — On-chain Groth16 proof verifier for RISC Zero
/// @notice Validates Groth16 proofs generated by RISC Zero's zkVM using the bn256
///         pairing precompile (EIP-197).
/// @dev Uses the official RISC Zero trusted setup VK (risc0-groth16 v1.2.6).
///      The Groth16 circuit has 5 public inputs, requiring IC[0]..IC[5].
///
///      RISC Zero seal format:
///        [4 bytes selector][256 bytes proof A,B,C][5 * 32 bytes public inputs]
///      where A is G1 (64 bytes), B is G2 (128 bytes), C is G1 (64 bytes).
///
///      The 5 public inputs encode the claim as split 128-bit limbs:
///        [claim_lo, claim_hi, control_root_lo, control_root_hi, bn254_control_id]
///
///      For ProofOfClaw, we reconstruct the claim from imageId + journalHash,
///      but we also accept a pre-encoded seal with public inputs embedded.
contract RiscZeroGroth16Verifier is IRiscZeroVerifier {

    // -----------------------------------------------------------------------
    // Official RISC Zero Verification Key (risc0-groth16 v1.2.6 trusted setup)
    // Source: risc0-ethereum/contracts/src/groth16/Groth16Verifier.sol
    // -----------------------------------------------------------------------

    // VK alpha (G1)
    uint256 constant VK_ALPHA_X = 20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 constant VK_ALPHA_Y = 9383485363053290200918347156157836566562967994039712273449902621266178545958;

    // VK beta (G2)
    uint256 constant VK_BETA_X1 = 4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 constant VK_BETA_X2 = 6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 constant VK_BETA_Y1 = 21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 constant VK_BETA_Y2 = 10505242626370262277552901082094356697409835680220590971873171140371331206856;

    // VK gamma (G2) — standard BN254 generator
    uint256 constant VK_GAMMA_X1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant VK_GAMMA_X2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant VK_GAMMA_Y1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant VK_GAMMA_Y2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;

    // VK delta (G2)
    uint256 constant VK_DELTA_X1 = 1668323501672964604911431804142266013250380587483576094566949227275849579036;
    uint256 constant VK_DELTA_X2 = 12043754404802191763554326994664886008979042643626290185762540825416902247219;
    uint256 constant VK_DELTA_Y1 = 7710631539206257456743780535472368339139328733484942210876916214502466455394;
    uint256 constant VK_DELTA_Y2 = 13740680757317479711909903993315946540841369848973133181051452051592786724563;

    // VK IC points (6 G1 points for 5 public inputs)
    uint256 constant VK_IC0_X = 8446592859352799428420270221449902464741693648963397251242447530457567083492;
    uint256 constant VK_IC0_Y = 1064796367193003797175961162477173481551615790032213185848276823815288302804;
    uint256 constant VK_IC1_X = 3179835575189816632597428042194253779818690147323192973511715175294048485951;
    uint256 constant VK_IC1_Y = 20895841676865356752879376687052266198216014795822152491318012491767775979074;
    uint256 constant VK_IC2_X = 5332723250224941161709478398807683311971555792614491788690328996478511465287;
    uint256 constant VK_IC2_Y = 21199491073419440416471372042641226693637837098357067793586556692319371762571;
    uint256 constant VK_IC3_X = 12457994489566736295787256452575216703923664299075106359829199968023158780583;
    uint256 constant VK_IC3_Y = 19706766271952591897761291684837117091856807401404423804318744964752784280790;
    uint256 constant VK_IC4_X = 19617808913178163826953378459323299110911217259216006187355745713323154132237;
    uint256 constant VK_IC4_Y = 21663537384585072695701846972542344484111393047775983928357046779215877070466;
    uint256 constant VK_IC5_X = 6834578911681792552110317589222010969491336870276623105249474534788043166867;
    uint256 constant VK_IC5_Y = 15060583660288623605191393599883223885678013570733629274538391874953353488393;

    // -----------------------------------------------------------------------
    // Constants
    // -----------------------------------------------------------------------

    // BN256 field modulus
    uint256 constant P = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
    // BN256 scalar field order
    uint256 constant Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Groth16 proof selector (first 4 bytes of seal)
    bytes4 public constant PROOF_SELECTOR = bytes4(0x310fe598);

    // -----------------------------------------------------------------------
    // Errors
    // -----------------------------------------------------------------------

    error InvalidSealLength();
    error InvalidProofSelector();
    error PairingFailed();
    error PrecompileFailed();

    // -----------------------------------------------------------------------
    // IRiscZeroVerifier implementation
    // -----------------------------------------------------------------------

    /// @notice Verify a RISC Zero Groth16 proof
    /// @param seal The Groth16 proof seal (selector + proof points + public inputs)
    /// @param imageId The RISC Zero guest program image ID
    /// @param journalHash SHA256 hash of the journal
    /// @dev The seal contains 4-byte selector + 256 bytes (A,B,C proof) + 5*32 bytes public inputs.
    ///      The public inputs encode the claim digest split into BN254 field elements.
    ///      We verify the embedded Groth16 proof against the hardcoded VK.
    function verify(
        bytes calldata seal,
        bytes32 imageId,
        bytes32 journalHash
    ) external view override {
        // Minimum seal: 4 (selector) + 64 (A) + 128 (B) + 64 (C) = 260 bytes
        // Full seal with public inputs: 260 + 5*32 = 420 bytes
        if (seal.length < 260) revert InvalidSealLength();

        // Check proof selector
        bytes4 selector = bytes4(seal[:4]);
        if (selector != PROOF_SELECTOR) revert InvalidProofSelector();

        // Decode Groth16 proof points from seal
        uint256 pA_x = uint256(bytes32(seal[4:36]));
        uint256 pA_y = uint256(bytes32(seal[36:68]));

        uint256 pB_x1 = uint256(bytes32(seal[68:100]));
        uint256 pB_x2 = uint256(bytes32(seal[100:132]));
        uint256 pB_y1 = uint256(bytes32(seal[132:164]));
        uint256 pB_y2 = uint256(bytes32(seal[164:196]));

        uint256 pC_x = uint256(bytes32(seal[196:228]));
        uint256 pC_y = uint256(bytes32(seal[228:260]));

        // Extract or compute public inputs
        uint256[5] memory pubInputs;
        if (seal.length >= 420) {
            // Public inputs embedded in seal (Bonsai/Boundless workflow)
            for (uint256 i = 0; i < 5; i++) {
                pubInputs[i] = uint256(bytes32(seal[260 + i * 32:292 + i * 32])) % Q;
            }
        } else {
            // Fallback: derive claim from imageId + journalHash (split into 128-bit limbs)
            bytes32 claimDigest = sha256(abi.encodePacked(imageId, journalHash));
            pubInputs[0] = uint256(uint128(uint256(claimDigest)));       // claim_lo
            pubInputs[1] = uint256(uint128(uint256(claimDigest) >> 128)); // claim_hi
            pubInputs[2] = 0; // control_root_lo (zero for simplified mode)
            pubInputs[3] = 0; // control_root_hi
            pubInputs[4] = 0; // bn254_control_id
        }

        // Compute vk_x = IC[0] + sum(pubInputs[i] * IC[i+1])
        (uint256 vkX_x, uint256 vkX_y) = _computeVkX(pubInputs);

        // Verify pairing: e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
        _verifyPairing(
            pA_x, pA_y,
            pB_x1, pB_x2, pB_y1, pB_y2,
            vkX_x, vkX_y,
            pC_x, pC_y
        );
    }

    // -----------------------------------------------------------------------
    // Internal — EC operations via precompiles
    // -----------------------------------------------------------------------

    /// @dev Compute vk_x = IC[0] + sum(pubInputs[i] * IC[i+1]) for i = 0..4
    function _computeVkX(
        uint256[5] memory pubInputs
    ) internal view returns (uint256, uint256) {
        // Start with IC[0]
        uint256 r_x = VK_IC0_X;
        uint256 r_y = VK_IC0_Y;

        // pubInputs[0] * IC[1]
        (uint256 t_x, uint256 t_y) = _ecMul(VK_IC1_X, VK_IC1_Y, pubInputs[0]);
        (r_x, r_y) = _ecAdd(r_x, r_y, t_x, t_y);

        // pubInputs[1] * IC[2]
        (t_x, t_y) = _ecMul(VK_IC2_X, VK_IC2_Y, pubInputs[1]);
        (r_x, r_y) = _ecAdd(r_x, r_y, t_x, t_y);

        // pubInputs[2] * IC[3]
        (t_x, t_y) = _ecMul(VK_IC3_X, VK_IC3_Y, pubInputs[2]);
        (r_x, r_y) = _ecAdd(r_x, r_y, t_x, t_y);

        // pubInputs[3] * IC[4]
        (t_x, t_y) = _ecMul(VK_IC4_X, VK_IC4_Y, pubInputs[3]);
        (r_x, r_y) = _ecAdd(r_x, r_y, t_x, t_y);

        // pubInputs[4] * IC[5]
        (t_x, t_y) = _ecMul(VK_IC5_X, VK_IC5_Y, pubInputs[4]);
        (r_x, r_y) = _ecAdd(r_x, r_y, t_x, t_y);

        return (r_x, r_y);
    }

    /// @dev Verify the Groth16 pairing equation using ecPairing precompile
    function _verifyPairing(
        uint256 pA_x, uint256 pA_y,
        uint256 pB_x1, uint256 pB_x2, uint256 pB_y1, uint256 pB_y2,
        uint256 vkX_x, uint256 vkX_y,
        uint256 pC_x, uint256 pC_y
    ) internal view {
        // Negate A: -A = (A.x, P - A.y)
        uint256 negA_y = pA_y == 0 ? 0 : P - pA_y;

        // Pairing input: 4 pairs of (G1, G2) points
        uint256[24] memory input;

        // Pair 1: (-A, B)
        input[0] = pA_x;
        input[1] = negA_y;
        input[2] = pB_x1;
        input[3] = pB_x2;
        input[4] = pB_y1;
        input[5] = pB_y2;

        // Pair 2: (alpha, beta)
        input[6] = VK_ALPHA_X;
        input[7] = VK_ALPHA_Y;
        input[8] = VK_BETA_X1;
        input[9] = VK_BETA_X2;
        input[10] = VK_BETA_Y1;
        input[11] = VK_BETA_Y2;

        // Pair 3: (vk_x, gamma)
        input[12] = vkX_x;
        input[13] = vkX_y;
        input[14] = VK_GAMMA_X1;
        input[15] = VK_GAMMA_X2;
        input[16] = VK_GAMMA_Y1;
        input[17] = VK_GAMMA_Y2;

        // Pair 4: (C, delta)
        input[18] = pC_x;
        input[19] = pC_y;
        input[20] = VK_DELTA_X1;
        input[21] = VK_DELTA_X2;
        input[22] = VK_DELTA_Y1;
        input[23] = VK_DELTA_Y2;

        uint256[1] memory result;
        bool success;

        assembly {
            success := staticcall(gas(), 0x08, input, 768, result, 32)
        }

        if (!success) revert PrecompileFailed();
        if (result[0] != 1) revert PairingFailed();
    }

    /// @dev EC point addition via precompile at 0x06
    function _ecAdd(
        uint256 x1, uint256 y1,
        uint256 x2, uint256 y2
    ) internal view returns (uint256, uint256) {
        uint256[4] memory input = [x1, y1, x2, y2];
        uint256[2] memory result;
        bool success;

        assembly {
            success := staticcall(gas(), 0x06, input, 128, result, 64)
        }

        if (!success) revert PrecompileFailed();
        return (result[0], result[1]);
    }

    /// @dev EC scalar multiplication via precompile at 0x07
    function _ecMul(
        uint256 x, uint256 y,
        uint256 s
    ) internal view returns (uint256, uint256) {
        uint256[3] memory input = [x, y, s];
        uint256[2] memory result;
        bool success;

        assembly {
            success := staticcall(gas(), 0x07, input, 96, result, 64)
        }

        if (!success) revert PrecompileFailed();
        return (result[0], result[1]);
    }
}
