// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./interfaces/IRiscZeroVerifier.sol";

/// @title RiscZeroGroth16Verifier — On-chain Groth16 proof verifier for RISC Zero
/// @notice Validates Groth16 proofs generated by RISC Zero's zkVM using the bn256
///         pairing precompile (EIP-197). The seal encodes a Groth16 proof (A, B, C points)
///         and the public inputs are derived from imageId and journalHash.
/// @dev The verification key (VK) is set at deployment and corresponds to the RISC Zero
///      trusted setup ceremony. The seal format is:
///        [4 bytes selector][256 bytes proof A,B,C][remaining bytes = extra data]
///      where A is G1 (64 bytes), B is G2 (128 bytes), C is G1 (64 bytes).
contract RiscZeroGroth16Verifier is IRiscZeroVerifier {
    // -----------------------------------------------------------------------
    // Verification Key — BN256 curve points from RISC Zero trusted setup
    // -----------------------------------------------------------------------

    // VK alpha point (G1)
    uint256 internal immutable VK_ALPHA_X;
    uint256 internal immutable VK_ALPHA_Y;

    // VK beta point (G2) — note G2 points have (x_im, x_re, y_im, y_re) layout
    uint256 internal immutable VK_BETA_X1;
    uint256 internal immutable VK_BETA_X2;
    uint256 internal immutable VK_BETA_Y1;
    uint256 internal immutable VK_BETA_Y2;

    // VK gamma point (G2)
    uint256 internal immutable VK_GAMMA_X1;
    uint256 internal immutable VK_GAMMA_X2;
    uint256 internal immutable VK_GAMMA_Y1;
    uint256 internal immutable VK_GAMMA_Y2;

    // VK delta point (G2)
    uint256 internal immutable VK_DELTA_X1;
    uint256 internal immutable VK_DELTA_X2;
    uint256 internal immutable VK_DELTA_Y1;
    uint256 internal immutable VK_DELTA_Y2;

    // VK IC (verification key for public inputs) — we need IC[0], IC[1], IC[2]
    // IC[0] is the base, IC[1] is for imageId input, IC[2] is for journalHash input
    uint256 internal immutable VK_IC0_X;
    uint256 internal immutable VK_IC0_Y;
    uint256 internal immutable VK_IC1_X;
    uint256 internal immutable VK_IC1_Y;
    uint256 internal immutable VK_IC2_X;
    uint256 internal immutable VK_IC2_Y;

    // -----------------------------------------------------------------------
    // Precompile addresses
    // -----------------------------------------------------------------------

    address constant EC_ADD = address(0x06);
    address constant EC_MUL = address(0x07);
    address constant EC_PAIRING = address(0x08);

    // BN256 curve order
    uint256 constant Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Groth16 proof selector (first 4 bytes of seal)
    bytes4 public immutable PROOF_SELECTOR;

    // -----------------------------------------------------------------------
    // Errors
    // -----------------------------------------------------------------------

    error InvalidSealLength();
    error InvalidProofSelector();
    error PairingFailed();
    error PrecompileFailed();

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    /// @notice Deploy with a complete Groth16 verification key
    /// @param vkAlpha G1 point [x, y]
    /// @param vkBeta G2 point [x1, x2, y1, y2]
    /// @param vkGamma G2 point [x1, x2, y1, y2]
    /// @param vkDelta G2 point [x1, x2, y1, y2]
    /// @param vkIC Array of G1 points [[x0,y0], [x1,y1], [x2,y2]]
    /// @param proofSelector 4-byte selector prepended to seals
    constructor(
        uint256[2] memory vkAlpha,
        uint256[4] memory vkBeta,
        uint256[4] memory vkGamma,
        uint256[4] memory vkDelta,
        uint256[6] memory vkIC,
        bytes4 proofSelector
    ) {
        VK_ALPHA_X = vkAlpha[0];
        VK_ALPHA_Y = vkAlpha[1];

        VK_BETA_X1 = vkBeta[0];
        VK_BETA_X2 = vkBeta[1];
        VK_BETA_Y1 = vkBeta[2];
        VK_BETA_Y2 = vkBeta[3];

        VK_GAMMA_X1 = vkGamma[0];
        VK_GAMMA_X2 = vkGamma[1];
        VK_GAMMA_Y1 = vkGamma[2];
        VK_GAMMA_Y2 = vkGamma[3];

        VK_DELTA_X1 = vkDelta[0];
        VK_DELTA_X2 = vkDelta[1];
        VK_DELTA_Y1 = vkDelta[2];
        VK_DELTA_Y2 = vkDelta[3];

        VK_IC0_X = vkIC[0];
        VK_IC0_Y = vkIC[1];
        VK_IC1_X = vkIC[2];
        VK_IC1_Y = vkIC[3];
        VK_IC2_X = vkIC[4];
        VK_IC2_Y = vkIC[5];

        PROOF_SELECTOR = proofSelector;
    }

    // -----------------------------------------------------------------------
    // IRiscZeroVerifier
    // -----------------------------------------------------------------------

    /// @notice Verify a RISC Zero Groth16 proof
    /// @param seal The Groth16 proof seal: [4-byte selector][64 bytes A][128 bytes B][64 bytes C]
    /// @param imageId The RISC Zero guest program image ID (public input 1)
    /// @param journalHash SHA256 hash of the journal (public input 2)
    /// @dev Reverts if the proof is invalid. The pairing equation checked is:
    ///      e(A, B) == e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
    ///      where vk_x = IC[0] + imageId * IC[1] + journalHash * IC[2]
    function verify(
        bytes calldata seal,
        bytes32 imageId,
        bytes32 journalHash
    ) external view override {
        // Minimum seal length: 4 (selector) + 64 (A) + 128 (B) + 64 (C) = 260
        if (seal.length < 260) revert InvalidSealLength();

        // Check proof selector
        bytes4 selector = bytes4(seal[:4]);
        if (selector != PROOF_SELECTOR) revert InvalidProofSelector();

        // Decode Groth16 proof points from seal
        // A is a G1 point (2 * 32 bytes)
        uint256 pA_x = uint256(bytes32(seal[4:36]));
        uint256 pA_y = uint256(bytes32(seal[36:68]));

        // B is a G2 point (2 * 2 * 32 bytes) — stored as (x_im, x_re, y_im, y_re)
        uint256 pB_x1 = uint256(bytes32(seal[68:100]));
        uint256 pB_x2 = uint256(bytes32(seal[100:132]));
        uint256 pB_y1 = uint256(bytes32(seal[132:164]));
        uint256 pB_y2 = uint256(bytes32(seal[164:196]));

        // C is a G1 point (2 * 32 bytes)
        uint256 pC_x = uint256(bytes32(seal[196:228]));
        uint256 pC_y = uint256(bytes32(seal[228:260]));

        // Compute public input scalars (reduced mod Q for the scalar field)
        uint256 input1 = uint256(imageId) % Q;
        uint256 input2 = uint256(journalHash) % Q;

        // Compute vk_x = IC[0] + input1 * IC[1] + input2 * IC[2]
        (uint256 vkX_x, uint256 vkX_y) = _computeVkX(input1, input2);

        // Verify pairing equation:
        //   e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
        // Which is equivalent to checking the product of pairings equals identity
        _verifyPairing(
            pA_x, pA_y,
            pB_x1, pB_x2, pB_y1, pB_y2,
            vkX_x, vkX_y,
            pC_x, pC_y
        );
    }

    // -----------------------------------------------------------------------
    // Internal — EC operations via precompiles
    // -----------------------------------------------------------------------

    /// @dev Compute vk_x = IC[0] + input1 * IC[1] + input2 * IC[2]
    function _computeVkX(
        uint256 input1,
        uint256 input2
    ) internal view returns (uint256, uint256) {
        // input1 * IC[1]
        (uint256 t1_x, uint256 t1_y) = _ecMul(VK_IC1_X, VK_IC1_Y, input1);

        // input2 * IC[2]
        (uint256 t2_x, uint256 t2_y) = _ecMul(VK_IC2_X, VK_IC2_Y, input2);

        // IC[0] + t1
        (uint256 r_x, uint256 r_y) = _ecAdd(VK_IC0_X, VK_IC0_Y, t1_x, t1_y);

        // r + t2
        (r_x, r_y) = _ecAdd(r_x, r_y, t2_x, t2_y);

        return (r_x, r_y);
    }

    /// @dev Verify the Groth16 pairing equation using ecPairing precompile
    function _verifyPairing(
        uint256 pA_x, uint256 pA_y,
        uint256 pB_x1, uint256 pB_x2, uint256 pB_y1, uint256 pB_y2,
        uint256 vkX_x, uint256 vkX_y,
        uint256 pC_x, uint256 pC_y
    ) internal view {
        // BN256 field modulus for negation
        uint256 P = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

        // Negate A: -A = (A.x, P - A.y)
        uint256 negA_y = pA_y == 0 ? 0 : P - pA_y;

        // Pairing input: 4 pairs of (G1, G2) points
        // e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
        uint256[24] memory input;

        // Pair 1: (-A, B)
        input[0] = pA_x;
        input[1] = negA_y;
        input[2] = pB_x1;
        input[3] = pB_x2;
        input[4] = pB_y1;
        input[5] = pB_y2;

        // Pair 2: (alpha, beta)
        input[6] = VK_ALPHA_X;
        input[7] = VK_ALPHA_Y;
        input[8] = VK_BETA_X1;
        input[9] = VK_BETA_X2;
        input[10] = VK_BETA_Y1;
        input[11] = VK_BETA_Y2;

        // Pair 3: (vk_x, gamma)
        input[12] = vkX_x;
        input[13] = vkX_y;
        input[14] = VK_GAMMA_X1;
        input[15] = VK_GAMMA_X2;
        input[16] = VK_GAMMA_Y1;
        input[17] = VK_GAMMA_Y2;

        // Pair 4: (C, delta)
        input[18] = pC_x;
        input[19] = pC_y;
        input[20] = VK_DELTA_X1;
        input[21] = VK_DELTA_X2;
        input[22] = VK_DELTA_Y1;
        input[23] = VK_DELTA_Y2;

        uint256[1] memory result;
        bool success;

        assembly {
            success := staticcall(gas(), 0x08, input, 768, result, 32)
        }

        if (!success) revert PrecompileFailed();
        if (result[0] != 1) revert PairingFailed();
    }

    /// @dev EC point addition via precompile at 0x06
    function _ecAdd(
        uint256 x1, uint256 y1,
        uint256 x2, uint256 y2
    ) internal view returns (uint256, uint256) {
        uint256[4] memory input = [x1, y1, x2, y2];
        uint256[2] memory result;
        bool success;

        assembly {
            success := staticcall(gas(), 0x06, input, 128, result, 64)
        }

        if (!success) revert PrecompileFailed();
        return (result[0], result[1]);
    }

    /// @dev EC scalar multiplication via precompile at 0x07
    function _ecMul(
        uint256 x, uint256 y,
        uint256 s
    ) internal view returns (uint256, uint256) {
        uint256[3] memory input = [x, y, s];
        uint256[2] memory result;
        bool success;

        assembly {
            success := staticcall(gas(), 0x07, input, 96, result, 64)
        }

        if (!success) revert PrecompileFailed();
        return (result[0], result[1]);
    }
}
